from checks import *

def tests():
    return [
        titleLayer('Vaade v_partiid'),
        getCheckColumnQuery('v_partiid', 'asula', points=1),
        getCheckColumnQuery('v_partiid', 'turniir', points=1),
        getCheckColumnQuery('v_partiid', 'algus', points=1),
        getCheckColumnQuery('v_partiid', 'valge_nimi', points=1),
        getCheckColumnQuery('v_partiid', 'valge_klubi', points=1),
        getCheckColumnQuery('v_partiid', 'valge_punkt', points=1),
        getCheckColumnQuery('v_partiid', 'must_nimi', points=1),
        getCheckColumnQuery('v_partiid', 'must_klubi', points=1),
        getCheckColumnQuery('v_partiid', 'must_punkt', points=1),
        getCheckDataQuery('v_partiid', 'COUNT(*)', expectedValue=299, points=1),

        titleLayer('Vaade v_partiidpisi'),
        getCheckColumnQuery('v_partiidpisi', 'id', points=1),
        getCheckColumnQuery('v_partiidpisi', 'valge_mangija', points=1),
        getCheckColumnQuery('v_partiidpisi', 'valge_punkt', points=1),
        getCheckColumnQuery('v_partiidpisi', 'must_mangija', points=1),
        getCheckColumnQuery('v_partiidpisi', 'must_punkt', points=1),
        getCheckDataQuery('v_partiidpisi', 'COUNT(*)', expectedValue=299, points=1),
        getCheckDataQuery('v_partiidpisi', 'valge_mangija', where='id = 10', expectedValue='Anna Raha', points=1),
        getCheckDataQuery('v_partiidpisi', 'must_mangija', where='id = 10', expectedValue='Aljona Aljas', points=1),
        getCheckDataQuery('v_partiidpisi', 'must_punkt', where='id = 10', expectedValue=0, points=1),
        getCheckDataQuery('v_partiidpisi', 'COUNT(*)', expectedValue=1, points=1),
        getCheckColumnQuery('v_partiidpisi', 'must_punkt', 'data_type', 'numeric', points=1),
        getCheckDataQuery('v_partiidpisi', 'must_punkt', where='id = 12', expectedValue=0.5, points=1),

        titleLayer('Vaade v_punktid'),
        getCheckColumnQuery('v_punktid', 'partii', points=1),
        getCheckColumnQuery('v_punktid', 'turniir', points=1),
        getCheckColumnQuery('v_punktid', 'mangija', points=1),
        getCheckColumnQuery('v_punktid', 'varv', points=1),
        getCheckColumnQuery('v_punktid', 'punkt', points=1),
        getCheckDataQuery('v_punktid', 'COUNT(*)', expectedValue=598, points=1),
        getCheckColumnQuery('v_punktid', 'partii', where="data_type LIKE 'int%'", points=1),
        getCheckColumnQuery('v_punktid', 'punkt', 'data_type', 'numeric', points=1),
        getCheckColumnQuery('v_punktid', 'varv', where="data_type LIKE 'varchar%' OR data_type LIKE 'text%'", points=1),
        getCheckColumnQuery('v_punktid', 'mangija', where="data_type LIKE 'int%'", points=1),
        getCheckDataQuery('v_punktid', 'COUNT(*)', where='partii = 299 AND mangija = 76', expectedValue=1, points=1),
        getCheckDataQuery('v_punktid', 'UPPER(varv)', where='partii = 299 AND mangija = 76', expectedValue='V', points=1),
        getCheckDataQuery('v_punktid', 'COUNT(*)', where='partii = 299 AND mangija = 85', expectedValue=1, points=1),
        getCheckDataQuery('v_punktid', 'UPPER(varv)', where='partii = 299 AND mangija = 85', expectedValue='M', points=1),
        getCheckDataQuery('v_punktid', 'COUNT(*)', where='partii = 299 AND mangija = 76', expectedValue=1, points=1),
        getCheckDataQuery('v_punktid', 'punkt', where='partii = 299 AND mangija = 76', dataType='float', expectedValue=0.5, points=1),
        getCheckDataQuery('v_punktid', 'COUNT(*)', where='partii = 11 AND mangija = 91', expectedValue=1, points=1),
        getCheckDataQuery('v_punktid', 'punkt', where='partii = 11 AND mangija = 91', dataType='float', expectedValue=0, points=1),
        getCheckDataQuery('v_punktid', 'COUNT(*)', where='partii = 1 AND mangija = 150', expectedValue=1, points=1),
        getCheckDataQuery('v_punktid', 'punkt', where='partii = 1 AND mangija = 150', dataType='float', expectedValue=1, points=1),

        titleLayer('Vaade v_edetabelid'),
        getCheckColumnQuery('v_edetabelid', 'id', points=1),
        getCheckColumnQuery('v_edetabelid', 'mangija', points=1),
        getCheckColumnQuery('v_edetabelid', 'synniaeg', points=1),
        getCheckColumnQuery('v_edetabelid', 'ranking', points=1),
        getCheckColumnQuery('v_edetabelid', 'klubi', points=1),
        getCheckColumnQuery('v_edetabelid', 'turniir', points=1),
        getCheckColumnQuery('v_edetabelid', 'punkte', points=1),
        getCheckDataQuery('v_edetabelid', 'COUNT(*)', expectedValue=184, points=1),

        titleLayer('Vaade mv_edetabelid'),
        getCheckDataQuery('pg_matviews', 'COUNT(*)', where="matviewname = 'mv_edetabelid'", schema='', expectedValue=1, points=1),
        getExecuteQuery('REFRESH MATERIALIZED VIEW mv_edetabelid'),
        getCheckDataQuery('mv_edetabelid', 'COUNT(*)', expectedValue=184, points=1),

        titleLayer('Vaade v_klubi54'),
        getCheckColumnQuery('v_klubi54', 'eesnimi', points=1),
        getCheckColumnQuery('v_klubi54', 'perenimi', points=1),
        getCheckColumnQuery('v_klubi54', 'synniaeg', points=1),
        getCheckColumnQuery('v_klubi54', 'ranking', points=1),
        getCheckColumnQuery('v_klubi54', 'klubi_id', points=1),
        getCheckDataQuery('v_klubi54', 'COUNT(*)', expectedValue=5, points=1),
        getCheckDataQuery('v_klubi54', 'klubi_id', where="eesnimi = 'Maria' AND perenimi = 'Lihtne'", expectedValue=54, points=1),

        titleLayer('Vaade v_maletaht'),
        getCheckColumnQuery('v_maletaht', 'id', points=1),
        getCheckColumnQuery('v_maletaht', 'eesnimi', points=1),
        getCheckColumnQuery('v_maletaht', 'perenimi', points=1),
        getCheckColumnQuery('v_maletaht', 'isikukood', points=1),
        getCheckColumnQuery('v_maletaht', 'klubis', points=1),
        getCheckColumnQuery('v_maletaht', 'synniaeg', points=1),
        getCheckColumnQuery('v_maletaht', 'sugu', points=1),
        getCheckColumnQuery('v_maletaht', 'ranking', points=1),
        getCheckDataQuery('v_maletaht', 'COUNT(*)', expectedValue=9, points=1),
    ]